### ISSUE TITLE
monster constantly at top of screen with just experience bar turned on

### ISSUE THREAD

**Issue by archenovalis** [mfoltz/Eclipse#1]
![image](https://github.com/user-attachments/assets/da3459a9-5f4e-451b-a2c4-0ba2b8bffefa)

overlaps with other things (like the wooden coffin)
![image](https://github.com/user-attachments/assets/6e730d74-11fc-4df4-9de6-0d65d4f851e2)

**Comment by archenovalis** [comment]
also, i'm level 10 but the bar shows full at level 9
![image](https://github.com/user-attachments/assets/797a4042-46b4-4d20-b958-2f55fd32fcbe)

**Comment by archenovalis** [comment]
another bug i noticed is that the experience bar slowly was falling behind. i'm now 20 and the bar is around 19 and 50%

**Comment by mfoltz** [comment]
got the extra bar at the top figured but haven't been able to replicate the mismatch you're seeing between bar and level/experience. might have something to do with single player (if this is single player you're doing) but not sure yet. try setting your level with the admin command then swap weapons and see what the bar does if you get the chance

**Comment by archenovalis** [comment]
i saw the xp bar freeze at 0% when it hit 16. sometime after 17 it was working again. might be the cause.
there's also a significant delay between getting a kill and the bar updating

**Comment by mfoltz** [comment]
The UI updates on the client every 2.5 seconds, it can probably handle more but would rather start low then increase if it seems fine instead of the opposite. Going to try sending updates in a coroutine from the server instead of only when kills are made, still haven’t managed to replicate the issues you’re seeing and would need more detail to diagnose further (single player? errors in console? does setting level manually with the admin command show progress as expected in bar or still have mismatches?)

**Comment by archenovalis** [comment]
rebuilt .dll using recent commits:
single player, mismatch disappeared when i logged in.

new issue:
single player, all bars enabled. was working great, then everything disappeared while i was building castle

**Comment by mfoltz** [comment]
it probably registered a click in the build menu at the same spot as the blood orb which hides the UI, I'll see about preventing that from doing anything when the user is in build mode. if that's the case can just click the orb again when done building

**Comment by archenovalis** [comment]
have no blood/feeble shows worker at level 0

**Comment by archenovalis** [comment]
![image](https://github.com/user-attachments/assets/43e48a7d-f5ab-4a9c-baf4-f6e5cfd12eba)
daily quest updated but not showing

**Comment by mfoltz** [comment]
think I spotted where frailed is getting turned into worker. hmm that's odd since if it doesn't work at the start not really sure why it would 10min later, something weird may be going on with the communication from server->client in single player but hopefully switching to updating through coroutine takes care of that. will do the bloodtype fix on the Bloodcraft end then do another release for that and Eclipse after, the quest windows seem to be misplaced for everyone but me 😂 so gonna change how the positioning for those works as well. don't think restedXP is being calculated correctly either so will be doing that as well and hopefully that'll fix it not updating the bar

**Comment by mfoltz** [comment]
all the issues mentioned here (except for possibly the delay between server->client updates in single player but hoping that got handled when changing the method of updating) should be handled, thank you for the testing and please reopen if you find any are persisting with the latest releases for Bloodcraft and Eclipse.
